export const countries = [
	{ label: "Afghanistan", value: "AF", code: "af", phone: "+93" },
	{ label: "Albania", value: "AL", code: "al", phone: "+355" },
	{ label: "Algeria", value: "DZ", code: "dz", phone: "+213" },
	{ label: "Andorra", value: "AD", code: "ad", phone: "+376" },
	{ label: "Angola", value: "AO", code: "ao", phone: "+244" },
	{ label: "Antigua and Barbuda", value: "AG", code: "ag", phone: "+1" },
	{ label: "Argentina", value: "AR", code: "ar", phone: "+54" },
	{ label: "Armenia", value: "AM", code: "am", phone: "+374" },
	{ label: "Australia", value: "AU", code: "au", phone: "+61" },
	{ label: "Austria", value: "AT", code: "at", phone: "+43" },
	{ label: "Azerbaijan", value: "AZ", code: "az", phone: "+994" },
	{ label: "Bahamas", value: "BS", code: "bs", phone: "+1" },
	{ label: "Bahrain", value: "BH", code: "bh", phone: "+973" },
	{ label: "Bangladesh", value: "BD", code: "bd", phone: "+880" },
	{ label: "Barbados", value: "BB", code: "bb", phone: "+1" },
	{ label: "Belarus", value: "BY", code: "by", phone: "+375" },
	{ label: "Belgium", value: "BE", code: "be", phone: "+32" },
	{ label: "Belize", value: "BZ", code: "bz", phone: "+501" },
	{ label: "Benin", value: "BJ", code: "bj", phone: "+229" },
	{ label: "Bhutan", value: "BT", code: "bt", phone: "+975" },
	{ label: "Bolivia", value: "BO", code: "bo", phone: "+591" },
	{ label: "Bosnia and Herzegovina", value: "BA", code: "ba", phone: "+387" },
	{ label: "Botswana", value: "BW", code: "bw", phone: "+267" },
	{ label: "Brazil", value: "BR", code: "br", phone: "+55" },
	{ label: "Brunei", value: "BN", code: "bn", phone: "+673" },
	{ label: "Bulgaria", value: "BG", code: "bg", phone: "+359" },
	{ label: "Burkina Faso", value: "BF", code: "bf", phone: "+226" },
	{ label: "Burundi", value: "BI", code: "bi", phone: "+257" },
	{ label: "Cabo Verde", value: "CV", code: "cv", phone: "+238" },
	{ label: "Cambodia", value: "KH", code: "kh", phone: "+855" },
	{ label: "Cameroon", value: "CM", code: "cm", phone: "+237" },
	{ label: "Canada", value: "CA", code: "ca", phone: "+1" },
	{
		label: "Central African Republic",
		value: "CF",
		code: "cf",
		phone: "+236",
	},
	{ label: "Chad", value: "TD", code: "td", phone: "+235" },
	{ label: "Chile", value: "CL", code: "cl", phone: "+56" },
	{ label: "China", value: "CN", code: "cn", phone: "+86" },
	{ label: "Colombia", value: "CO", code: "co", phone: "+57" },
	{ label: "Comoros", value: "KM", code: "km", phone: "+269" },
	{
		label: "Congo (Congo-Brazzaville)",
		value: "CG",
		code: "cg",
		phone: "+242",
	},
	{ label: "Costa Rica", value: "CR", code: "cr", phone: "+506" },
	{ label: "Croatia", value: "HR", code: "hr", phone: "+385" },
	{ label: "Cuba", value: "CU", code: "cu", phone: "+53" },
	{ label: "Cyprus", value: "CY", code: "cy", phone: "+357" },
	{
		label: "Czechia (Czech Republic)",
		value: "CZ",
		code: "cz",
		phone: "+420",
	},
	{ label: "Denmark", value: "DK", code: "dk", phone: "+45" },
	{ label: "Djibouti", value: "DJ", code: "dj", phone: "+253" },
	{ label: "Dominica", value: "DM", code: "dm", phone: "+1" },
	{ label: "Dominican Republic", value: "DO", code: "do", phone: "+1" },
	{ label: "Ecuador", value: "EC", code: "ec", phone: "+593" },
	{ label: "Egypt", value: "EG", code: "eg", phone: "+20" },
	{ label: "El Salvador", value: "SV", code: "sv", phone: "+503" },
	{ label: "Equatorial Guinea", value: "GQ", code: "gq", phone: "+240" },
	{ label: "Eritrea", value: "ER", code: "er", phone: "+291" },
	{ label: "Estonia", value: "EE", code: "ee", phone: "+372" },
	{ label: "Eswatini", value: "SZ", code: "sz", phone: "+268" },
	{ label: "Ethiopia", value: "ET", code: "et", phone: "+251" },
	{ label: "Fiji", value: "FJ", code: "fj", phone: "+679" },
	{ label: "Finland", value: "FI", code: "fi", phone: "+358" },
	{ label: "France", value: "FR", code: "fr", phone: "+33" },
	{ label: "Gabon", value: "GA", code: "ga", phone: "+241" },
	{ label: "Gambia", value: "GM", code: "gm", phone: "+220" },
	{ label: "Georgia", value: "GE", code: "ge", phone: "+995" },
	{ label: "Germany", value: "DE", code: "de", phone: "+49" },
	{ label: "Ghana", value: "GH", code: "gh", phone: "+233" },
	{ label: "Greece", value: "GR", code: "gr", phone: "+30" },
	{ label: "Grenada", value: "GD", code: "gd", phone: "+1" },
	{ label: "Guatemala", value: "GT", code: "gt", phone: "+502" },
	{ label: "Guinea", value: "GN", code: "gn", phone: "+224" },
	{ label: "Guinea-Bissau", value: "GW", code: "gw", phone: "+245" },
	{ label: "Guyana", value: "GY", code: "gy", phone: "+592" },
	{ label: "Haiti", value: "HT", code: "ht", phone: "+509" },
	{ label: "Honduras", value: "HN", code: "hn", phone: "+504" },
	{ label: "Hungary", value: "HU", code: "hu", phone: "+36" },
	{ label: "Iceland", value: "IS", code: "is", phone: "+354" },
	{ label: "India", value: "IN", code: "in", phone: "+91" },
	{ label: "Indonesia", value: "ID", code: "id", phone: "+62" },
	{ label: "Iran", value: "IR", code: "ir", phone: "+98" },
	{ label: "Iraq", value: "IQ", code: "iq", phone: "+964" },
	{ label: "Ireland", value: "IE", code: "ie", phone: "+353" },
	{ label: "Israel", value: "IL", code: "il", phone: "+972" },
	{ label: "Italy", value: "IT", code: "it", phone: "+39" },
	{ label: "Jamaica", value: "JM", code: "jm", phone: "+1" },
	{ label: "Japan", value: "JP", code: "jp", phone: "+81" },
	{ label: "Jordan", value: "JO", code: "jo", phone: "+962" },
	{ label: "Kazakhstan", value: "KZ", code: "kz", phone: "+7" },
	{ label: "Kenya", value: "KE", code: "ke", phone: "+254" },
	{ label: "Kiribati", value: "KI", code: "ki", phone: "+686" },
	{ label: "Korea, North", value: "KP", code: "kp", phone: "+850" },
	{ label: "Korea, South", value: "KR", code: "kr", phone: "+82" },
	{ label: "Kosovo", value: "XK", code: "xk", phone: "+383" },
	{ label: "Kuwait", value: "KW", code: "kw", phone: "+965" },
	{ label: "Kyrgyzstan", value: "KG", code: "kg", phone: "+996" },
	{ label: "Laos", value: "LA", code: "la", phone: "+856" },
	{ label: "Latvia", value: "LV", code: "lv", phone: "+371" },
	{ label: "Lebanon", value: "LB", code: "lb", phone: "+961" },
	{ label: "Lesotho", value: "LS", code: "ls", phone: "+266" },
	{ label: "Liberia", value: "LR", code: "lr", phone: "+231" },
	{ label: "Libya", value: "LY", code: "ly", phone: "+218" },
	{ label: "Liechtenstein", value: "LI", code: "li", phone: "+423" },
	{ label: "Lithuania", value: "LT", code: "lt", phone: "+370" },
	{ label: "Luxembourg", value: "LU", code: "lu", phone: "+352" },
	{ label: "Madagascar", value: "MG", code: "mg", phone: "+261" },
	{ label: "Malawi", value: "MW", code: "mw", phone: "+265" },
	{ label: "Malaysia", value: "MY", code: "my", phone: "+60" },
	{ label: "Maldives", value: "MV", code: "mv", phone: "+960" },
	{ label: "Mali", value: "ML", code: "ml", phone: "+223" },
	{ label: "Malta", value: "MT", code: "mt", phone: "+356" },
	{ label: "Marshall Islands", value: "MH", code: "mh", phone: "+692" },
	{ label: "Mauritania", value: "MR", code: "mr", phone: "+222" },
];
